var trueString1 = bool('true')
var trueString2 = bool('trUe')
var falseString1  = bool('false')
var falseString2 = bool('falSe')
var trueInt2 = bool(2)
var trueInt1 = bool(1)
var trueIntNeg1 = bool(-1)
var falseInt0 = bool(0)
